DROP TABLE IF EXISTS textDatabase;

CREATE TABLE textDatabase (
    itemNum INTEGER,
    textEntered TEXT NOT NULL,
    encodedVectorEntry1 INTEGER,
    encodedVectorEntry2 INTEGER,
    encodedVectorEntry3 INTEGER,
    encodedVectorEntry4 INTEGER,
    encodedVectorEntry5 INTEGER,
    encodedVectorEntry6 INTEGER,
    encodedVectorEntry7 INTEGER,
    encodedVectorEntry8 INTEGER,
    encodedVectorEntry9 INTEGER,
    encodedVectorEntry10 INTEGER,
    encodedVectorEntry11 INTEGER,
    encodedVectorEntry12 INTEGER,
    encodedVectorEntry13 INTEGER,
    encodedVectorEntry14 INTEGER,
    encodedVectorEntry15 INTEGER,
    encodedVectorEntry16 INTEGER,
    encodedVectorEntry17 INTEGER,
    encodedVectorEntry18 INTEGER,
    encodedVectorEntry19 INTEGER,
    encodedVectorEntry20 INTEGER,
    encodedVectorEntry21 INTEGER,
    encodedVectorEntry22 INTEGER,
    encodedVectorEntry23 INTEGER,
    encodedVectorEntry24 INTEGER,
    encodedVectorEntry25 INTEGER,
);