DROP TABLE IF EXISTS textDatabase;

CREATE TABLE textDatabase (
    itemNum INTEGER,
    textEntered TEXT NOT NULL,
    encodedVectorEntry1 FLOAT,
    encodedVectorEntry2 FLOAT,
    encodedVectorEntry3 FLOAT,
    encodedVectorEntry4 FLOAT,
    encodedVectorEntry5 FLOAT,
    encodedVectorEntry6 FLOAT,
    encodedVectorEntry7 FLOAT,
    encodedVectorEntry8 FLOAT,
    encodedVectorEntry9 FLOAT,
    encodedVectorEntry10 FLOAT,
    encodedVectorEntry11 FLOAT,
    encodedVectorEntry12 FLOAT,
    encodedVectorEntry13 FLOAT,
    encodedVectorEntry14 FLOAT,
    encodedVectorEntry15 FLOAT,
    encodedVectorEntry16 FLOAT,
    encodedVectorEntry17 FLOAT,
    encodedVectorEntry18 FLOAT,
    encodedVectorEntry19 FLOAT,
    encodedVectorEntry20 FLOAT,
    encodedVectorEntry21 FLOAT,
    encodedVectorEntry22 FLOAT,
    encodedVectorEntry23 FLOAT,
    encodedVectorEntry24 FLOAT,
    encodedVectorEntry25 FLOAT
);